{{- $values := .Values -}}
{{- $template := .Template }}
{{- $chart := .Chart -}}
{{- $release := .Release -}}
{{- $files := .Files }}
{{- $capabilities := .Capabilities -}}
{{- $global := .Values.global }}
{{- if ne (kindOf $global) "map" }}
  {{- $global = dict "namespace"  .Release.Namespace }}
  {{- $global = merge $global (dict "serviceAccount" (dict "create" true)) }}
{{- end}}

{{- $porterAgent := $values.porterAgent }}

{{- /* validate values */ -}}
{{- if not (eq (kindOf $porterAgent) "map")}}
  {{- fail "No Configuration found for .Values.porterAgent" }}
{{- end }}
{{- /* we need a minimum of container image references */ -}}
{{- if or (ne (kindOf $porterAgent.image) "map") (not $porterAgent.image.repository) }}
  {{- fail "No Configuration found for .Values.porterAgent.image" }}
{{- end }}

{{- /* default values */ -}}
{{- if not $porterAgent.namespace }}
  {{- $porterAgent = merge (dict "namespace" $global.namespace) $porterAgent }}
  {{- if not $porterAgent.namespace }}
    {{- $porterAgent = merge (dict "namespace" .Release.Namespace) $porterAgent }}
  {{- end }}
{{- end }}
{{- if not $porterAgent.serviceAccount }}  
  {{- $porterAgent = merge (dict "serviceAccount" $global.serviceAccount) $porterAgent}}
{{- end }}

{{- /* create the final values */ -}}
{{- $values = merge (dict "global" $global) $values}}
  
{{- $values = merge (dict "porterAgent" $porterAgent) $values}}
{{- $data := merge (dict "Files" $files) (dict "Values" $values) (dict "Capabilities" $capabilities) (dict "Chart" $chart) (dict "Release" $release) (dict "Template" $template)}}
---
{{- include "porter-agent.agentConfig" $data }}
---
{{- include "porter-agent.configSecret" $data }}
---
{{- include "porter-agent.envSecret" $data }}
---
{{- if or $values.porterAgent.serviceAccount.agent.create $values.porterAgent.serviceAccount.create -}}
  {{- include "porter-agent.agentServiceAccount" $data }}
{{- end }}
---
{{- if or $values.porterAgent.serviceAccount.installation.create $values.porterAgent.serviceAccount.create -}}
  {{- include "porter-agent.installationServiceAccount" $data }}

{{- end }}
---
{{- if $values.porterAgent.rbac.create -}}
  {{- include "porter-agent.clusterRole" $data }}
---
  {{- include "porter-agent.roleBinding" $data }}
---
  {{- include "porter-agent.installationClusterRole" $data }}
---
  {{- include "porter-agent.installationClusterRoleBinding" $data }}
{{- end}}
---