FROM python:3.11-alpine3.21

RUN apk add curl vim
COPY mkdocs-requirements.txt /tmp/.
RUN python -m pip install -r /tmp/mkdocs-requirements.txt
EXPOSE 8080
WORKDIR /docs
ENTRYPOINT ["mkdocs"]
CMD ["serve", "--dev-addr=0.0.0.0:8000"]
