
# environment refers to either of "onPrem" "saas" "marketPlace"
# "saas" "marketPlace" are used by Kinetica only
# for a customer trying to install the chart on his own wherever, it should be onPrem
environment: "onPrem"
# onPrem Providers: "k3s" "kind" "eks" "aks" "other"
# saas Providers: eks
# marketPlace Providers: aks eks
provider: k3s


nodeSelector: {}
tolerations: []
affinity: {}

ingressNginx:
  install: true
"ingress-nginx":
  controller:
    kind: DaemonSet
    allowSnippetAnnotations: true
    hostNetwork: true
    hostPort:
      enabled: true
    service:
      enabled: false
    publishService:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: false
    config:
      use-forwarded-headers: "true"
    
openldap:
  namespace: "gpudb"
  fullnameOverride: "openldap"
  env:
    LDAP_BACKEND: "mdb"
    LDAP_ORGANISATION: "Kinetica DB Inc."
    LDAP_DOMAIN: "kinetica.com"
    LDAP_LOG_LEVEL: "128"
  affinity: {}
  podAntiAffinity: {}
  persistence:
    enabled: true
    existingClaim: ""
    accessMode: "ReadWriteOnce"
    size: 1Mi
    storageClass: "local-path"

supportBundle:
  install: true
"support-bundle":
  configMap:
    # NOTE: Should match the 'db.name' of the KineticaCluster you are creating -
    #       affects the filename of the support-bundles that are created to create
    #       additional tracability.
    cluster: "kinetica-k3s-sample"

kineticacluster:
  install: true
  name: kinetica-k3s-sample
  stats:
    isEnabled: false
  gpudbCluster:
    clusterName: kinetica-k3s-sample
    # You need a license key. Please contact support@kinetica.com
    license: ""
    hasPools: false
    config:
      tieredStorage:
        globalTier:
          colocateDisks: true
        persistTier:
          default:
            limit: ""
            provisioner: "rancher.io/local-path"
            volumeClaim:
              spec:
                storageClassName: "local-path"
        

dbAdminUser:
  create: true

workbench:
  install: true
  storageClass: kinetica-k3s-sample-storageclass
