otel-collector-config: |-
  receivers:
    # Make sure to add the otlp receiver.
    # This will open up the receiver on port 4317
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
  processors:
  extensions:
    health_check: {}
    zpages: {}
  exporters:
    otlphttp:
      endpoint: "simplest-collector.kinetica-system.svc.cluster.local:4417"
    prometheus:
      endpoint: 0.0.0.0:8889
      namespace: "kinetica-system"
    logging:
  service:
    extensions: [health_check, zpages]
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [otlphttp, logging]

      metrics:
        receivers: [otlp]
        processors: []
        exporters: [prometheus, logging]
