{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "support-bundle.serviceAccountName" . }}-role-cr
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ""
    resources:
      - secrets
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ""
    resources:
      - configmaps
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - "storageclasses"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "support-bundle.serviceAccountName" . }}-role-crb
roleRef:
  kind: ClusterRole
  name: {{ include "support-bundle.serviceAccountName" . }}-role-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "support-bundle.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "support-bundle.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "support-bundle.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
