{{ if not .Values.existingSecret }}
{{- $config_password := (randAlphaNum 32)| b64enc | quote -}}
{{- $values := merge (dict "configPassword" $config_password) .Values -}}



apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.openldapNamespace | default "gpudb"}}
  namespace: {{ .Values.openldapNamespace | default "gpudb"}}
  name: {{ template "openldap.fullname" . }}
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
stringData:
  LDAP_ADMIN_USERNAME: "{{ .Values.global.configUser }}"
  {{- $old_sec := lookup "v1" "Secret" .Release.Namespace "openldap" }}
  {{- if or (not $old_sec) (not $old_sec.data) }}
  LDAP_ADMIN_PASSWORD: {{ .Values.adminPassword | default (randAlphaNum 32) | b64enc | quote }}
  LDAP_CONFIG_PASSWORD: {{ $values.configPassword  }}
  {{/* LDAP_CONFIG_ADMIN_PASSWORD is the variable required by the bitnami image, keeping both for backward compatibility */}}  
  LDAP_CONFIG_ADMIN_PASSWORD: {{ $values.configPassword   }}
  {{ else }}
  LDAP_ADMIN_PASSWORD: {{ index $old_sec.data "LDAP_ADMIN_PASSWORD" }}
  LDAP_CONFIG_PASSWORD: {{ index $old_sec.data "LDAP_CONFIG_PASSWORD" }}
  LDAP_CONFIG_ADMIN_PASSWORD: {{ index $old_sec.data "LDAP_CONFIG_ADMIN_PASSWORD" }}
  {{ end }}
{{ end }}
