
{{- $values := .Values -}}
{{- $template := .Template }}
{{- $chart := .Chart -}}
{{- $release := .Release -}}
{{- $files := .Files }}
{{- $capabilities := .Capabilities -}}
{{- $global := .Values.global }}
{{- if ne (kindOf $global) "map" }}
  {{- $global = dict "namespace"  .Release.Namespace }}
  {{- $global = merge $global (dict "serviceAccount" (dict "create" true)) }}
{{- end}}


{{- $porterOperator := $values.porterOperator }}

{{- /* validate values */ -}}
{{- if not (eq (kindOf $porterOperator) "map")}}
  {{- fail "No Configuration found for .Values.porterOperator" }}
{{- end }}
{{- /* we need a minimum of proxy and manager container image references */ -}}
{{- if or (ne (kindOf $porterOperator.proxy) "map") (ne (kindOf $porterOperator.proxy.image) "map") (not $porterOperator.proxy.image.repository) (not $porterOperator.proxy.image.tag) }}
  {{- fail "No Configuration found for .Values.porterOperator.proxy.image" }}
{{- end }}
{{- if or (ne (kindOf $porterOperator.manager) "map") (ne (kindOf $porterOperator.manager.image) "map") (not $porterOperator.manager.image.repository) }}
  {{- fail "No Configuration found for .Values.porterOperator.manager.image" }}
{{- end }}

{{- /* default values */ -}}
{{- if not $porterOperator.namespace }}
  {{- $porterOperator = merge (dict "namespace" $global.namespace) $porterOperator }}
  {{- if not $porterOperator.namespace }}
    {{- $porterOperator = merge (dict "namespace" .Release.Namespace) $porterOperator }}
  {{- end}}
{{- end }}    
{{- if not $porterOperator.serviceAccount }}  
  {{- $porterOperator = merge (dict "serviceAccount" $global.serviceAccount) $porterOperator }}
{{- end }}
{{- if or (not $porterOperator.rbac) (eq (kindOf $porterOperator.rbac) "map")}}
  {{- $porterOperator = merge (dict "rbac" (dict "create" true)) $porterOperator }}
{{- end }}
{{- if not $porterOperator.replicas }}
  {{- $porterOperator = merge (dict "replicas" 1) $porterOperator }}
{{- end }}
{{- if not $porterOperator.podSecurityContext }}
  {{- $porterOperator = merge (dict "podSecurityContext" (dict "runAsUser" 65532)) $porterOperator }}
{{- end }}
{{- if not $porterOperator.proxy.containerPort }}
  {{- $porterOperator = merge (dict "proxy" (dict "containerPort" 8443)) $porterOperator }}
{{- end }}
{{- if not $porterOperator.manager.probePort }}
  {{- $porterOperator = merge (dict "manager" (dict "probePort" 8081)) $porterOperator }}
{{- end }}


{{- /* create the final values */ -}}
{{- $values = merge (dict "global" $global) $values}}
  
{{- $values = merge (dict "porterOperator" $porterOperator) $values}}
{{- $data := merge (dict "Files" $files) (dict "Values" $values) (dict "Capabilities" $capabilities) (dict "Chart" $chart) (dict "Release" $release) (dict "Template" $template)}}
---
{{- include "porter-operator.deployment" $data }}
---
{{- include "porter-operator.metricsService" $data }}
---
{{- include "porter-operator.configMap" $data }}
---
{{- if $values.porterOperator.serviceAccount.create -}}
  {{- include "porter-operator.serviceAccount" $data }}
{{- end }}
---
{{- if $values.porterOperator.rbac.create -}}
  {{- include "porter-operator.leaderElectionRole" $data }}
---
  {{- include "porter-operator.leaderElectionRoleBinding" $data }}
---
  {{- include "porter-operator.managerRole" $data }}
---
  {{- include "porter-operator.managerRoleBinding" $data }}
---
  {{- include "porter-operator.metricsReaderRole" $data }}
---
  {{- include "porter-operator.metricsReaderRoleBinding" $data }}
---
  {{- include "porter-operator.proxyRole" $data }}
---
  {{- include "porter-operator.proxyRoleBinding" $data }}
{{- end }}
---

